### PR TITLE
Update to ember-cli 0.2.6 and other minor tweaks

### PR DESCRIPTION
**Pull request by salzhrani**
Also use `Ember.run.bind` for `boundCallback`

### CODE REVIEW

**Comment by HamptonMakes** [comment]
This looks great. It was my first addon and I didn't know my way around as well... so thanks!

**Comment by salzhrani** [comment]
You are welcome

**Comment by salzhrani** [comment]
Can we have a release please?

**Comment by HamptonMakes** [comment]
Only thing I need to fix is that I had a test failure when running locally and need to debug before release.

—

**Comment by salzhrani** [comment]
Awesome!

**Pull request merged**
